// import styles from '@/styles/Home.module.css'
import React, { useContext, useEffect, useState } from "react";

import { AppContext } from "@/context/AppContext";
import Head from "next/head";
import { Inter } from "@next/font/google";
import TdHighlCon from "@/components/TdHighlCon";
import TodayCon from "@/components/TodayCon";
import WeekCon from "@/components/WeekCon";
import { data } from "@/data";
import useConvert from "@/utils/useConvert";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const { handleGeoCodeClick, weatherData } = useContext(AppContext);

  useEffect(() => {
    handleGeoCodeClick("berlin");
    //eslint-disable-next-line
  }, []);

  console.log("weatherData", weatherData);
  return (
    <>
      <Head>
        <title>Weather Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {weatherData && (
        <main className="main-con grid gap-0 md:grid-cols-[30%_70%] auto-rows-auto grid-flow-row pr-3 pl-3 pb-5">
          <TodayCon />

          <div className="grid-div-row-2 grid md:grid-rows-[50% 50%] md:h-[90vh] md:col-start-2 md:col-end-auto md:row-start-1 md: row-end-auto content-center">
            <WeekCon />

            <TdHighlCon />
          </div>
        </main>
      )}
      {!weatherData && <div>Loading...</div>}
    </>
  );
}
