// import styles from '@/styles/Home.module.css'
import { useEffect, useState } from "react";

import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import SearchBarCon from "@/components/SearchBarCon";
import TodayCon from "@/components/TodayCon";
import cloudIcon from "../../public/cloud-icon.png";
import { data } from "@/data";
import humidityIcon from "../../public/humidity-icon.png";
import useGeoCode from "@/utils/useGeoCode";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [weatherData, setWeatherData] = useState(null);
  const [searchInput, setSearchInput] = useState({
    city: "",
  });
  const [checkInput, setCheckInput] = useState(false);

  const { getGeoCodeFunc, foreCastWeather } = useGeoCode();

  const handleSearchInputChange = (e) => {
    setSearchInput((prevState) => ({ ...prevState, city: e.target.value }));
  };
  const handleGeoCodeClick = async (cityString) => {
    const city = !searchInput.city ? { city: cityString } : searchInput;
    if (city.city) {
      const geoData = await getGeoCodeFunc(city);
      console.log("geoData: ", geoData);
      const foreCast = await foreCastWeather(geoData[0].lat, geoData[0].lon);
      console.log("foreCast: ", foreCast);
      setCheckInput(false);
      setWeatherData(foreCast.data);
      setSearchInput((prevState) => ({ ...prevState, city: "" }));
    } else {
      console.log("error :>> ");
      return setCheckInput(true);
    }
  };

  useEffect(() => {
    handleGeoCodeClick("berlin");
    //eslint-disable-next-line
  }, []);
  // console.log("searchInput: ", searchInput);
  console.log("weatherData", weatherData);
  return (
    <>
      <Head>
        <title>Weather Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {weatherData && (
        <main className="main-con grid gap-0 grid-cols-1 sm:grid-cols-2  auto-rows-auto pr-3 pl-3">
          <div className="today-con grid gap-1 grid-cols-1  gap-y-1 auto-rows-auto pb-6">
            <SearchBarCon
              handleGeoCodeClick={handleGeoCodeClick}
              handleSearchInputChange={handleSearchInputChange}
              searchInput={searchInput}
            />

            <TodayCon weatherData={weatherData} />

            <div className="today-con-description ">
              <figure className="today-con_description_icon flex mt-2">
                <Image
                  className="inline-block w-auto h-auto"
                  src={`https://openweathermap.org/img/wn/${weatherData.current.weather[0].icon}@2x.png`}
                  alt="current weather icon"
                  width="20"
                  height="20"
                  blurDataURL="blur"
                  priority="true"
                />
                <figcaption className="pl-2">
                  {weatherData.current.weather[0].description}
                </figcaption>
              </figure>

              <figure className="today-con_description_icon flex mt-2 ">
                <Image
                  className="inline-block w-auto h-auto"
                  src={humidityIcon}
                  alt="current weather icon"
                  width="20"
                  height="20"
                  blurDataURL="blur"
                  priority="true"
                />
                <figcaption className="pl-2">
                  Humidity: {weatherData.current.humidity}%
                </figcaption>
              </figure>

              <figure className="today-con_description_icon flex mt-2 ">
                <Image
                  className="inline-block w-auto h-auto"
                  src={cloudIcon}
                  alt="current weather icon"
                  width="20"
                  height="20"
                  blurDataURL="blur"
                  priority="true"
                />
                <figcaption className="pl-2">
                  Clouds: {weatherData.current.clouds}%
                </figcaption>
              </figure>
            </div>
          </div>

          <div className="details-con grid gap-1 grid-cols-1 grid-rows-4">
            <div className="border-2">B1</div>
            <div className="border-2">B2</div>
            <div className="border-2">B3</div>
            <div className="border-2">B4</div>
          </div>
        </main>
      )}
      {!weatherData && <div>Loading...</div>}
    </>
  );
}
